### ISSUE TITLE
ignore source if not present

### ISSUE THREAD

**Issue by aronwc** [dungngo99/fhf-qa-chatbot#5]
https://github.com/dungngo99/fhf-qa-chatbot/blob/72b855958bef06af10e56c53ae656b7b33b3b99f/app/utilities/filewriter.py#L54

When no source is present in the google sheet, rather than printing "SOURCE: Can't find the source. Please try again!", just don't print anything. So, if source is empty or not present, return "".

**Comment by DylanN-code** [comment]
issue resolved!
